### ISSUE TITLE
Requirement File

### ISSUE THREAD

**Issue by ahsuriya** [sEhsanTaher/Beheshti-NER#2]
Requirement file missing error occurs.
Please elaborate the step 4 of requirement.txt file or upload the file
Thank You

**Comment by nightfury96** [comment]
Yes PlZ upload req
where are the codes???

**Comment by ParsaHejabi** [comment]
Exactly,
There are neither `requirements.txt` file nor `BERT-NER directory` in the repository.
Could you please update the repo?

**Comment by pejmangholami** [comment]
yes please upload all reduirement file like main.py and etc.

**Comment by sEhsanTaher** [comment]
The issue was solved.
